name = "codenames-duet"
compatibility_date = "2024-12-18"
pages_build_output_dir = "public"

[durable_objects]
bindings = [
  { name = "GAME_STATE", class_name = "GameState", script_name = "codenames-duet-worker" }
]

[[kv_namespaces]]
binding = "RATE_LIMIT"
preview_id = "749ebb2f2f8c4bbe80c0ea7b3924d2a9"
id = "dc817117f5044174abb7ba45f93b986d"